apiVersion: v2
name: nebulous
description: Umbrella chart for Water monitoring scenario demo
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: suricata-log-processor
    version: 0.1.0
    repository: "file://charts/suricata-log-processor"
    condition: suricata-log-processor.enabled
  - name: water-flow-monitor
    version: 0.1.0
    repository: "file://charts/water-flow-monitor"
    condition: water-flow-monitor.enabled
  - name: ems-server
    version: 0.1.0
    repository: "file://charts/ems-server"
    condition: ems-server.enabled
