apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "suricata-log-processor.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  BROKER_USERNAME: {{ .Values.config.brokerUsername | quote }}
