apiVersion: v1
kind: Secret
metadata:
  name: {{ include "suricata-log-processor.fullname" . }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  BROKER_PASSWORD: {{ .Values.secret.brokerPassword | quote }}
